
import "./globals.css";

export const metadata = {
  title: "fundHive app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className= "text-2xl font-semibold"
      >
        {children}
      </body>
    </html>
  );
}
